CREATE TABLE blog_posts (
    id INT( 6 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    title VARCHAR( 500 ) DEFAULT NULL ,
    text VARCHAR( 10000 ) DEFAULT NULL ,
    category VARCHAR( 50 ) DEFAULT NULL ,
    tags VARCHAR( 100 ) DEFAULT NULL ,
    url VARCHAR(500) DEFAULT NULL UNIQUE,
    created_on DATETIME NOT NULL ,
    updated_on TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);